# Generated by Django 4.2.23 on 2025-07-18 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_promobanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.AddField(
            model_name='product',
            name='audio_sample',
            field=models.FileField(blank=True, null=True, upload_to='products/audio/', verbose_name='Пример аудио (MP3, WAV)'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(blank=True, default=dict, help_text='Физические и технические данные, например: {"Вес": "250 г", "Диаметр динамика": "40 мм"}', verbose_name='Тех. характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='functionality',
            field=models.JSONField(blank=True, default=dict, help_text='Ключевые особенности, например: {"Шумоподавление": "Активное (ANC)", "Тип подключения": "Bluetooth 5.2"}', verbose_name='Функционал'),
        ),
        migrations.CreateModel(
            name='ProductInfoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок карточки')),
                ('text', models.TextField(verbose_name='Текст карточки')),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='URL ссылки (например, на видеообзор)')),
                ('link_text', models.CharField(blank=True, max_length=50, null=True, verbose_name="Текст для ссылки (например, 'Смотреть обзор')")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_cards', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Информационная карточка товара',
                'verbose_name_plural': 'Информационные карточки товара',
            },
        ),
    ]
