# Generated by Django 4.2.23 on 2025-07-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_specifications_product_audio_sample_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinfocard',
            options={'verbose_name': 'Инфо-карточка (фича)', 'verbose_name_plural': 'Инфо-карточки (фичи)'},
        ),
        migrations.RemoveField(
            model_name='productinfocard',
            name='link_text',
        ),
        migrations.RemoveField(
            model_name='productinfocard',
            name='text',
        ),
        migrations.AddField(
            model_name='productinfocard',
            name='image',
            field=models.ImageField(default='', upload_to='products/info_cards/', verbose_name='Фото для карточки (квадратное)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productinfocard',
            name='link_url',
            field=models.URLField(default='#', verbose_name='URL для перехода по клику'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productinfocard',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок (под фото)'),
        ),
    ]
