# Generated by Django 4.2.23 on 2025-07-18 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productinfocard_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название правила (для админа)')),
                ('discount_type', models.CharField(choices=[('TOTAL_QTY', 'На общее количество товаров в корзине'), ('PRODUCT_QTY', 'На количество конкретного товара'), ('CATEGORY_QTY', 'На количество товаров из конкретной категории')], default='TOTAL_QTY', max_length=20, verbose_name='Тип скидки')),
                ('min_quantity', models.PositiveIntegerField(default=2, verbose_name='Минимальное количество для активации')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Например, 10.5 для 10.5%', max_digits=5, verbose_name='Процент скидки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Правило активно')),
                ('category_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Целевая категория')),
                ('product_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Целевой товар')),
            ],
            options={
                'verbose_name': 'Правило скидки',
                'verbose_name_plural': 'Правила скидок',
                'ordering': ['-discount_percentage'],
            },
        ),
    ]
