# Generated by Django 4.2.23 on 2025-07-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_discountrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='shop.product', verbose_name='Сопутствующие товары'),
        ),
    ]
