# Generated by Django 4.2.23 on 2025-07-20 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_related_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name="Название группы (например, 'Чехол для iPhone 15 Pro')")),
            ],
            options={
                'verbose_name': 'Группа цветов',
                'verbose_name_plural': 'Группы цветов',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='color_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.colorgroup', verbose_name='Группа цветов'),
        ),
    ]
